config/routes.rb
Rails.application.routes.draw do
  resources :locations
  resources :vehicles
  
  root 'welcome#index'

  get 'about' => 'welcome#about'

  get 'contact' => 'welcome#contact'

end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :vehicles
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  belongs_to :location
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @vehicle = Vehicle.new
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:lot)
    end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:make, :label, :year, :miles, :category, :price, :avatar, :location_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dealership</title>
  <meta charset="utf=8"
  <meta http=equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Dealership", root_path, class:"navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
          <li><%= link_to "Vehicles", vehicles_path %></li>
          <li><%= link_to "Locations", locations_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="container">
  <%= yield %>
  </div>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lot %><br>
    <%= f.text_field :lot %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Locations</h1>

<div class="panel panel-default">
    <% @locations.each do |location| %>
      <div class="panel-body">
        <h2><%= link_to location.lot, location %></h2>
        <%= link_to 'Edit', edit_location_path(location), class: "btn btn-primary" %> |
        <%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>

<br>

<%= link_to 'New Location', new_location_path, class: "btn btn-primary" %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<h1><strong>Lot: </strong><%= @location.lot %></h1>

<% @location.vehicles.each do |car| %>
<p><%= car.make %> <%= car.label %></p>
<% end %>


<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/vehicles/_form.html.erb
<%= form_for(@vehicle) do |f| %>
  <% if @vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% @vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :make %><br>
    <%= f.text_field :make, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :label %><br>
    <%= f.text_field :label, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :year %><br>
    <%= f.number_field :year, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :miles %><br>
    <%= f.number_field :miles, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :category %><br>
    <%= f.text_field :category, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :price %><br>
    <%= f.number_field :price, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label "Photo" %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="field form-group">
    <%= f.collection_select(:location_id, Location.all, :id, :lot) %>
  </div>
  <div class="actions form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form' %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehicles</h1>

<div class="row">
    <% @vehicles.each do |vehicle| %>
      <div class="col-md-4">
       <div class="panel panel-default">
        <div class="panel-body">
         <h3><%= vehicle.make %></h3>
         <h3><%= vehicle.label %></h3>
         <p>Year: <%= vehicle.year %></p>
         <p>Miles: <%= vehicle.miles %></p>
         <p><%= vehicle.category %></p>
         <p>$<%= vehicle.price %></p>
         <% if vehicle.avatar_file_name != nil %>
         <%= image_tag vehicle.avatar.url(:medium), class: "img-responsive" %>
         <% end %>
         <div class="btn-group">
          <%= link_to 'Show', vehicle, class: "btn btn-primary" %>
          <%= link_to 'Edit', edit_vehicle_path(vehicle), class: "btn btn-success" %>
          <%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
         </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<br>

<%= link_to 'New Vehicle', new_vehicle_path, class: "btn btn-primary" %>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form' %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Make:</strong>
  <%= @vehicle.make %>
</p>

<p>
  <strong>Label:</strong>
  <%= @vehicle.label %>
</p>

<p>
  <strong>Year:</strong>
  <%= @vehicle.year %>
</p>

<p>
  <strong>Miles:</strong>
  <%= @vehicle.miles %>
</p>

<p>
  <strong>Category:</strong>
  <%= @vehicle.category %>
</p>

<p>
  <strong>Price:</strong>
  <%= @vehicle.price %>
</p>

<%= image_tag @vehicle.avatar.url(:medium) %>
</br>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>

app/views/welcome/about.html.erb
<h1>About Us</h1>
<p>We are dedicated to providing the ultimate service along with the best possible vehicle to help our customers remove any transportation related stress from their lives</p>

app/views/welcome/contact.html.erb
<div class="jumbotron">
  <h1>Contact Us</h1>
  <p>We can be reached in several ways</p>
</div>

<div class="row">
  <div class="col-md-4">
    <div class="jumbotron">
      <h3>Email Us</h3>
      <p>Please feel free to email us at help@dealership.com</p>
    </div>
  </div>
  <div class="col-md-4">
    <div class="jumbotron">
      <h3>Call Us</h3>
      <p>Call our toll free help line at 1-888-GET-HELP</p>
    </div>
  </div>
  <div class="col-md-4">
    <div class="jumbotron">
      <h3>Stop By</h3>
      <p>Stop by your local branch located at:</p>
      <p>1234 Main Street</p>
      <p>Local Town, ST 10001</p>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron">
    <h1>Auto Dealership</h1>
    <p>Welcome to our dealership! We offer only the finest new and used cars for your purchase.</p>
</div>

<div class="row">
  <div class="col-md-6">
    <div class="jumbotron">
      <h2>Great Deals!</h2>
      <p>We have great deals 24/7!</p>
    </div>
  </div>
  <div class="col-md-6">
    <div class="jumbotron">
      <h2>Friendly and Helpful Staff!</h2>
      <p>You can always contact one of our knowledgeable employees to help you pick out the perfect car!</p>
    </div>
  </div>
</div>